In [1]:
import numpy as np
y=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
# array of elements in the third element from all the rows
third_elemnets=[]
print("The array of third element from all columns")
for i in y:
    third_elemnets.append(i[2])
third_array=np.array(third_elemnets)
print(third_array)


The array of third element from all columns
[ 9 21 33 45 57]


In [2]:
#Build a new array from above swapping first and last
swap = y[::,::-1]
print(swap)

[[12  9  6  3]
 [24 21 18 15]
 [36 33 30 27]
 [48 45 42 39]
 [60 57 54 51]]


In [8]:
#build a new array of odd rows and even columns 
new_array=y[::2,1::2]
print(y)
print(new_array)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [4]:
#Swap rows and columns in  reverse order
tranpose=y[::-1,::-1]
print(" Array After Swap rows and columns in reverse order ")
print(tranpose)

 Array After Swap rows and columns in reverse order 
[[60 57 54 51]
 [48 45 42 39]
 [36 33 30 27]
 [24 21 18 15]
 [12  9  6  3]]


In [5]:
# Get all items between 7 and 20 from b
b=np.array([13,6,11,19,10,3,27])
index = np.where((b > 7) & (b < 25))
print(b[index])

[13 11 19 10]


In [6]:
#identify the index of 6th repetition of 5 in array
x=np.array([5,2,5,5,3,4,3,5,5,2,5,5,2])
c=0
for i in range(0,len(x)):
  if(x[i]==5):
    c=c+1
    if(c==6):
      print("the index of 6th repetition of 5 in array is ",i+1)
      break

the index of 6th repetition of 5 in array is  11
