In [10]:
# Eigen Values and Eigen Vectors of the given matrix
import numpy as np
arr =np.array([[ 4,-1],[2,0]])
w,v=np.linalg.eig(arr)
print("The Eigen values:-",w)
print("The Eigen vectors:-\n",v)


The Eigen values:- [3.41421356 0.58578644]
The Eigen vectors:-
 [[0.86285621 0.28108464]
 [0.50544947 0.95968298]]


In [11]:
#Building an 2x3 array comprising of 6 normally distributed random numbers with mean 12 and standard deviation 10.
from numpy import random
x = random.normal(size=(2, 3),loc=12,scale=10)
print("An 2x3 array comprising of 6 normally distributed random numbers with mean 12 and standard deviation 10:--\n",x)


An 2x3 array comprising of 6 normally distributed random numbers with mean 12 and standard deviation 10:--
 [[17.14166717 29.75907934 14.01836117]
 [13.68814562  5.1294526  22.8998369 ]]


In [16]:
#Construct a program to create a 6x6 array with random values
#find the minimum and maximum values
import numpy as np
arr = np.random.random((6,6))
print("Array:\n",arr) 
arrmin=arr.min()
arrmax=arr.max()
print("Minimum Value of the array:--",arrmin)
print("Maximum Value of the array:--",arrmax)

Array:
[[0.62576362 0.07765091 0.28293767 0.19089695 0.96192769 0.11197353]
 [0.00568046 0.89910532 0.30098329 0.85036302 0.35673064 0.00525857]
 [0.73929445 0.71674399 0.57417545 0.71549516 0.28940589 0.18855227]
 [0.64926849 0.49435703 0.24354775 0.45861413 0.36248699 0.80140323]
 [0.32701041 0.51881838 0.75244219 0.6225237  0.13319041 0.32003072]
 [0.15968115 0.33691195 0.47745409 0.08184549 0.97882906 0.99440583]]
Minimum Value of the array:-- 0.005258566777959772
Maximum Value of the array:-- 0.9944058297591419
